# Generated by Django 5.0.3 on 2024-04-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
